name: "example"
on:
  workflow_dispatch:
jobs:
  build: # spin up a virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Happy Birthday, Chris!"

