name: "example"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build: # spin up a virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4.6.0
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest 
